site_name: HatLab_IOT_Wiki
site_description: HatLab_IOT_Wiki
site_author: HatLab Team members
site_url: https://dassecurity-labs.github.io/HatLab_IOT_Wiki/




copyright: 'Copyright &copy; 2020 HatLab Team'




# setting nav and deploy page
nav:
    - Introduction:
        - 基本介绍/Intro: index.md
        - 内容概述/Summary: summary.md
        - 关于我们/About: about.md 
        
    - 无线电安全:

        - 蓝牙安全:
            - 基础攻防知识:
                - Class of Device: wireless_security/bluetooth_security/base_intro/Class_of_Device.md
                - Active Scanning vs. Passive Scanning: wireless_security/bluetooth_security/base_intro/Active_Scanning_vs_Passive_Scanning.md
    
                
#        - ZigBee 安全:
#            - 概述: index.md




    - 固件安全:
        - 概述: firmware_security/index.md
        - 固件分类: firmware_security/firmware_sort.md
        - 固件获取: 
            - 概述: firmware_security/firmware_obtain/index.md
            - 官网下载: firmware_security/firmware_obtain/website_download.md
            - 更新抓包获取: firmware_security/firmware_obtain/update_captrue.md
  
        - IOT 设备指令集特点:
            - 敏感函数定位技巧: firmware_security/IOT_instructions_charac/found_danger_func.md
            - 栈溢出利用技巧: firmware_security/IOT_instructions_charac/stackoverflow_exploit.md
        - 环境搭建:
            - fuzzing 环境搭建: firmware_security/environment_building/Mips_fuzzing_environment_building.md

        - 总结性文章:
            - C 语言中字符分割有关的函数与常见字符串复制溢出点: firmware_security/summary_article/string_vulnerability.md
    - 硬件安全:
        - 概述: hardware_security/index.md

    - 工具库:
        - 概述: tools_lib/index.md
        - 固件安全工具: tools_lib/firmware_tools/index.md
        


theme:
  name: 'material'
  
  palette:
    primary: 'Light Blue'
    accent: 'Deep Orange'
  
  feature:
    tabs: true

  logo:
    icon: 'cloud'
  language: 'zh'



extra:
  social:
    - type: 'github'
      link: 'https://github.com/DasSecurity-Labs'
    - type: 'twitter'
      link: 'https://twitter.com/H4looo'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
